server:
  port: 8081

spring:
  application:
    name: job-executor-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ""
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    publisher-confirm-type: correlated
    publisher-returns: true
    
logging:
  level:
     com.scheduler: DEBUG
     org.springframework.amqp: INFO
     org.springframework.jdbc.core: DEBUG
     org.springframework.jdbc.datasource: DEBUG